In [ ]:
import pandas as pd
import numpy as np

In [13]:
data = pd.read_csv('data.csv')

In [14]:
data.shape

(545778, 49)

In [15]:
data.head(2)

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item,product_id,...,distribution_center_geom,order_item_id,delivery_longitude,delivery_latitude,warehouse_name,warehouse_longitude,warehouse_latitude,is_loyal,product_name_clean,customer_review
0,118730,94911,Shipped,F,2026-03-11 00:47:27+00:00,NaN,2026-03-12 20:06:27+00:00,NaN,1,2200,...,POINT(-89.9711 35.1174),172697,-92.088678,34.127955,Memphis TN,-89.9711,35.1174,False,Bella Two-Tone Full-Zip Hooded Sweatshirt,Just received the Bella Two-Tone Full-Zip Hood...
1,114939,91961,Shipped,M,2026-03-11 00:46:02+00:00,NaN,2026-03-13 23:10:02+00:00,NaN,2,21920,...,POINT(-95.3698 29.7604),167157,-119.645815,36.534992,Houston TX,-95.3698,29.7604,False,Calvin Klein Sportswear Men's Broken Micro Che...,I really liked this Calvin Klein Sportswear Me...

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545778 entries, 0 to 545777
Data columns (total 49 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   order_id                        545778 non-null  int64
 1   user_id                         545778 non-null  int64
 2   status                          545778 non-null  object
 3   gender                          545778 non-null  object
 4   created_at                      545778 non-null  object
 5   returned_at                     54174 non-null   object
 6   shipped_at                      354054 non-null  object
 7   delivered_at                    190125 non-null  object
 8   num_of_item                     545778 non-null  int64
 9   product_id                      545778 non-null  int64
 10  inventory_item_id               545778 non-null  int64
 11  sale_price                      545778 non-null  float64
 12  id                              545778 non-null  int64
 13  first_name                      545778 non-null  object
 14  last_name                       545778 non-null  object
 15  email                           545778 non-null  object
 16  age                             545778 non-null  int64
 17  state                           545778 non-null  object
 18  street_address                  545778 non-null  object
 19  postal_code                     545778 non-null  object
 20  city                            540324 non-null  object
 21  country                         545778 non-null  object
 22  traffic_source                  545778 non-null  object
 23  user_geom                       545778 non-null  object
 24  cost                            545778 non-null  float64
 25  category                        545778 non-null  object
 26  brand                           545226 non-null  object
 27  retail_price                    545778 non-null  float64
 28  department                      545778 non-null  object
 29  sku                             545778 non-null  object
 30  distribution_center_id          545778 non-null  int64
 31  sold_at                         0 non-null       float64
 32  product_category                545778 non-null  object
 33  product_name                    545757 non-null  object
 34  product_brand                   545226 non-null  object
 35  product_retail_price            545778 non-null  float64
 36  product_department              545778 non-null  object
 37  product_sku                     545778 non-null  object
 38  product_distribution_center_id  545778 non-null  int64
 39  distribution_center_geom        545778 non-null  object
 40  order_item_id                   545778 non-null  int64
 41  delivery_longitude              545778 non-null  float64
 42  delivery_latitude               545778 non-null  float64
 43  warehouse_name                  545778 non-null  object
 44  warehouse_longitude             545778 non-null  float64
 45  warehouse_latitude              545778 non-null  float64
 46  is_loyal                        545778 non-null  bool
 47  product_name_clean              545757 non-null  object
 48  customer_review                 545778 non-null  object
dtypes: bool(1), float64(9), int64(10), object(29)
memory usage: 200.4+ MB

In [17]:
data.columns

Index(['order_id', 'user_id', 'status', 'gender', 'created_at', 'returned_at',
       'shipped_at', 'delivered_at', 'num_of_item', 'product_id',
       'inventory_item_id', 'sale_price', 'id', 'first_name', 'last_name',
       'email', 'age', 'state', 'street_address', 'postal_code', 'city',
       'country', 'traffic_source', 'user_geom', 'cost', 'category', 'brand',
       'retail_price', 'department', 'sku', 'distribution_center_id',
       'sold_at', 'product_category', 'product_name', 'product_brand',
       'product_retail_price', 'product_department', 'product_sku',
       'product_distribution_center_id', 'distribution_center_geom',
       'order_item_id', 'delivery_longitude', 'delivery_latitude',
       'warehouse_name', 'warehouse_longitude', 'warehouse_latitude',
       'is_loyal', 'product_name_clean', 'customer_review'],
      dtype='object')



*   Поменять формат данных у created_at, returned_at , shipped_at, delivered_at - с object ---> date
*   Удалить столбец sold_at, так как во всех строках нет значений


*   Проверить столбцы с похожими названиями на полное совпадение (по типу brand --- product_brand)
*   Столбцы postal_code -- возможно тоже поменять формат


*   Удалить дублирующиеся строки

### Удалим дубликаты

In [18]:
data.duplicated().sum()

np.int64(363852)

In [19]:
data[data.duplicated(keep= False)].sort_values(by=list(data.columns)).head(5)

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item,product_id,...,distribution_center_geom,order_item_id,delivery_longitude,delivery_latitude,warehouse_name,warehouse_longitude,warehouse_latitude,is_loyal,product_name_clean,customer_review
95917,1,1,Complete,M,2024-10-14 10:31:40+00:00,NaN,2024-10-14 20:11:40+00:00,2024-10-19 07:17:40+00:00,1,22533,...,POINT(-118.25 34.05),1,-90.627780,41.588617,Los Angeles CA,-118.2500,34.05,False,KingSize Big & Tall Expandable Waist Wrinkle R...,Just received the KingSize Big & Tall Expandab...
277843,1,1,Complete,M,2024-10-14 10:31:40+00:00,NaN,2024-10-14 20:11:40+00:00,2024-10-19 07:17:40+00:00,1,22533,...,POINT(-118.25 34.05),1,-90.627780,41.588617,Los Angeles CA,-118.2500,34.05,False,KingSize Big & Tall Expandable Waist Wrinkle R...,Just received the KingSize Big & Tall Expandab...
459769,1,1,Complete,M,2024-10-14 10:31:40+00:00,NaN,2024-10-14 20:11:40+00:00,2024-10-19 07:17:40+00:00,1,22533,...,POINT(-118.25 34.05),1,-90.627780,41.588617,Los Angeles CA,-118.2500,34.05,False,KingSize Big & Tall Expandable Waist Wrinkle R...,Just received the KingSize Big & Tall Expandab...
73772,2,2,Complete,F,2025-04-11 13:43:06+00:00,NaN,2025-04-13 07:54:06+00:00,2025-04-16 08:37:06+00:00,2,12982,...,POINT(-90.0667 29.95),3,15.726955,51.221528,New Orleans LA,-90.0667,29.95,True,Lucky Brand My Tribe Banded Halter Top,"As a frequent shopper, I'm thrilled with this ..."
255698,2,2,Complete,F,2025-04-11 13:43:06+00:00,NaN,2025-04-13 07:54:06+00:00,2025-04-16 08:37:06+00:00,2,12982,...,POINT(-90.0667 29.95),3,15.726955,51.221528,New Orleans LA,-90.0667,29.95,True,Lucky Brand My Tribe Banded Halter Top,"As a frequent shopper, I'm thrilled with this ..."

In [20]:
data1 = data.drop_duplicates()
# оставит первое вхождение

In [21]:
data1.shape

(181926, 49)

In [22]:
data1.columns

Index(['order_id', 'user_id', 'status', 'gender', 'created_at', 'returned_at',
       'shipped_at', 'delivered_at', 'num_of_item', 'product_id',
       'inventory_item_id', 'sale_price', 'id', 'first_name', 'last_name',
       'email', 'age', 'state', 'street_address', 'postal_code', 'city',
       'country', 'traffic_source', 'user_geom', 'cost', 'category', 'brand',
       'retail_price', 'department', 'sku', 'distribution_center_id',
       'sold_at', 'product_category', 'product_name', 'product_brand',
       'product_retail_price', 'product_department', 'product_sku',
       'product_distribution_center_id', 'distribution_center_geom',
       'order_item_id', 'delivery_longitude', 'delivery_latitude',
       'warehouse_name', 'warehouse_longitude', 'warehouse_latitude',
       'is_loyal', 'product_name_clean', 'customer_review'],
      dtype='object')

### Проверим столбцы на схожесть

In [23]:
col = data1.columns
col
to_del = []

for i in range(len(col)):
  for j in range(i+1, len(col)):
    if data1[data1.columns[i]].equals(data1[data1.columns[j]]):
      print(f"{col[i]:<23} | {col[j]:<23}")
      to_del.append(col[j])

user_id                 | id
sale_price              | retail_price
sale_price              | product_retail_price
category                | product_category
brand                   | product_brand
retail_price            | product_retail_price
department              | product_department
sku                     | product_sku
distribution_center_id  | product_distribution_center_id
product_name            | product_name_clean

In [24]:
data1[['user_geom', 'delivery_longitude', 'delivery_latitude',  'distribution_center_geom', 'warehouse_longitude', 'warehouse_latitude']]

,user_geom,delivery_longitude,delivery_latitude,distribution_center_geom,warehouse_longitude,warehouse_latitude
0,POINT(-92.0886782 34.12795471),-92.088678,34.127955,POINT(-89.9711 35.1174),-89.9711,35.1174
1,POINT(-119.6458146 36.53499187),-119.645815,36.534992,POINT(-95.3698 29.7604),-95.3698,29.7604
2,POINT(-119.6458146 36.53499187),-119.645815,36.534992,POINT(-75.1667 39.95),-75.1667,39.9500
3,POINT(116.5019973 39.83631574),116.501997,39.836316,POINT(-87.6847 41.8369),-87.6847,41.8369
4,POINT(2.45549956 48.98550893),2.455500,48.985509,POINT(-118.25 34.05),-118.2500,34.0500
...,...,...,...,...,...,...
181921,POINT(-62.4853718 -7.362417987),-62.485372,-7.362418,POINT(-87.6847 41.8369),-87.6847,41.8369
181922,POINT(-62.4853718 -7.362417987),-62.485372,-7.362418,POINT(-88.0431 30.6944),-88.0431,30.6944
181923,POINT(-62.4853718 -7.362417987),-62.485372,-7.362418,POINT(-89.9711 35.1174),-89.9711,35.1174
181924,POINT(-62.4853718 -7.362417987),-62.485372,-7.362418,POINT(-95.3698 29.7604),-95.3698,29.7604
181925,POINT(-95.46179389 29.58265204),-95.461794,29.582652,POINT(-79.9333 32.7833),-79.9333,32.7833

In [25]:
import re

def extract_coords(point_str):
    match = re.search(r'POINT\(([-\d.]+)\s+([-\d.]+)\)', point_str)
    if match:
        return float(match.group(1)), float(match.group(2))
    return None, None


data1['user_longitude'] = data1['user_geom'].apply(lambda x: extract_coords(x)[0])
data1['user_latitude'] = data1['user_geom'].apply(lambda x: extract_coords(x)[1])

longitude_match = data1['user_longitude'] == data1['delivery_longitude']
latitude_match = data1['user_latitude'] == data1['delivery_latitude']

coords_match = longitude_match & latitude_match #булевы

print(f"Совпадающих координат: {coords_match.sum()}")
print(f"Не совпадающих: {(~coords_match).sum()}")

data1 = data1.drop(columns= ['user_longitude', 'user_latitude'])

/tmp/ipykernel_5926/2005638555.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['user_longitude'] = data1['user_geom'].apply(lambda x: extract_coords(x)[0])

Совпадающих координат: 181926
Не совпадающих: 0

/tmp/ipykernel_5926/2005638555.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['user_latitude'] = data1['user_geom'].apply(lambda x: extract_coords(x)[1])

In [26]:
def extract_coords_dist(point_str):
    match = re.search(r'POINT\(([-\d.]+)\s+([-\d.]+)\)', point_str)
    if match:
        return float(match.group(1)), float(match.group(2))
    return None, None


data1['dist_longitude'] = data1['distribution_center_geom'].apply(lambda x: extract_coords(x)[0])
data1['dist_latitude'] = data1['distribution_center_geom'].apply(lambda x: extract_coords(x)[1])

longitude_match = data1['dist_longitude'] == data1['warehouse_longitude']
latitude_match = data1['dist_latitude'] == data1['warehouse_latitude']

coords_match = longitude_match & latitude_match

print(f"Совпадающих координат: {coords_match.sum()}")
print(f"Не совпадающих: {(~coords_match).sum()}")

data1 = data1.drop(columns= ['dist_longitude', 'dist_latitude'])

Совпадающих координат: 181926
Не совпадающих: 0

In [27]:
to_del.append('distribution_center_geom')
to_del.append('user_geom')

data_clean = data1.drop(columns= to_del)

In [28]:
data_clean.shape

(181926, 38)

In [29]:
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 181926 entries, 0 to 181925
Data columns (total 38 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_id                181926 non-null  int64
 1   user_id                 181926 non-null  int64
 2   status                  181926 non-null  object
 3   gender                  181926 non-null  object
 4   created_at              181926 non-null  object
 5   returned_at             18058 non-null   object
 6   shipped_at              118018 non-null  object
 7   delivered_at            63375 non-null   object
 8   num_of_item             181926 non-null  int64
 9   product_id              181926 non-null  int64
 10  inventory_item_id       181926 non-null  int64
 11  sale_price              181926 non-null  float64
 12  first_name              181926 non-null  object
 13  last_name               181926 non-null  object
 14  email                   181926 non-null  object
 15  age                     181926 non-null  int64
 16  state                   181926 non-null  object
 17  street_address          181926 non-null  object
 18  postal_code             181926 non-null  object
 19  city                    180108 non-null  object
 20  country                 181926 non-null  object
 21  traffic_source          181926 non-null  object
 22  cost                    181926 non-null  float64
 23  category                181926 non-null  object
 24  brand                   181742 non-null  object
 25  department              181926 non-null  object
 26  sku                     181926 non-null  object
 27  distribution_center_id  181926 non-null  int64
 28  sold_at                 0 non-null       float64
 29  product_name            181919 non-null  object
 30  order_item_id           181926 non-null  int64
 31  delivery_longitude      181926 non-null  float64
 32  delivery_latitude       181926 non-null  float64
 33  warehouse_name          181926 non-null  object
 34  warehouse_longitude     181926 non-null  float64
 35  warehouse_latitude      181926 non-null  float64
 36  is_loyal                181926 non-null  bool
 37  customer_review         181926 non-null  object
dtypes: bool(1), float64(7), int64(8), object(22)
memory usage: 52.9+ MB

### Изменим формат некоторых данных

In [31]:
data_clean

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item,product_id,...,sold_at,product_name,order_item_id,delivery_longitude,delivery_latitude,warehouse_name,warehouse_longitude,warehouse_latitude,is_loyal,customer_review
0,118730,94911,Shipped,F,2026-03-11 00:47:27+00:00,NaN,2026-03-12 20:06:27+00:00,NaN,1,2200,...,NaN,Bella Two-Tone Full-Zip Hooded Sweatshirt,172697,-92.088678,34.127955,Memphis TN,-89.9711,35.1174,False,Just received the Bella Two-Tone Full-Zip Hood...
1,114939,91961,Shipped,M,2026-03-11 00:46:02+00:00,NaN,2026-03-13 23:10:02+00:00,NaN,2,21920,...,NaN,Calvin Klein Sportswear Men's Broken Micro Che...,167157,-119.645815,36.534992,Houston TX,-95.3698,29.7604,False,I really liked this Calvin Klein Sportswear Me...
2,114939,91961,Shipped,M,2026-03-11 00:46:02+00:00,NaN,2026-03-13 23:10:02+00:00,NaN,2,20031,...,NaN,FactoryExtreme Neptune Men's Black Biker Leath...,167158,-119.645815,36.534992,Philadelphia PA,-75.1667,39.9500,False,Nice FactoryExtreme Neptune Men's Black Biker ...
3,99949,79993,Complete,F,2026-03-11 00:39:44.268552+00:00,NaN,2026-03-13 17:24:44.268552+00:00,2026-03-16 01:00:44.268552+00:00,1,15500,...,NaN,HUE Women's 3-Pack Hidden Cotton Liner,145310,116.501997,39.836316,Chicago IL,-87.6847,41.8369,False,Nice HUE Women's 3-Pack Hidden Cotton Liner. W...
4,92967,74352,Shipped,M,2026-03-11 00:39:29.765939+00:00,NaN,2026-03-12 11:30:29.765939+00:00,NaN,1,18572,...,NaN,Zorrel - Insect Shield Apparel Long Sleeve Tee...,135249,2.455500,48.985509,Los Angeles CA,-118.2500,34.0500,False,Good value for money. The Zorrel - Insect Shie...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181921,32199,25808,Shipped,F,2019-01-10 19:40:10+00:00,NaN,2019-01-13 00:21:10+00:00,NaN,4,10095,...,NaN,Midnight By Carole Hochman Women's Swept Away ...,46856,-62.485372,-7.362418,Chicago IL,-87.6847,41.8369,True,"As a frequent shopper, I'm thrilled with this ..."
181922,32199,25808,Shipped,F,2019-01-10 19:40:10+00:00,NaN,2019-01-13 00:21:10+00:00,NaN,4,1836,...,NaN,American Apparel Unisex Dolman Sleeve Hoodie,46858,-62.485372,-7.362418,Mobile AL,-88.0431,30.6944,True,Another 5-star purchase! This American Apparel...
181923,32199,25808,Shipped,F,2019-01-10 19:40:10+00:00,NaN,2019-01-13 00:21:10+00:00,NaN,4,14985,...,NaN,Adjustable Bra Design Front Panel Clasp Matern...,46855,-62.485372,-7.362418,Memphis TN,-89.9711,35.1174,True,"I always order my gear here, and this Adjustab..."
181924,32199,25808,Shipped,F,2019-01-10 19:40:10+00:00,NaN,2019-01-13 00:21:10+00:00,NaN,4,7231,...,NaN,Jones New York Women's Boot Skirt,46857,-62.485372,-7.362418,Houston TX,-95.3698,29.7604,True,Best brand ever. This Jones New York Women's B...
181925,21439,17102,Processing,F,2019-01-04 03:52:40+00:00,NaN,NaN,NaN,1,9952,...,NaN,Soft Cotton Sleepwear Pajamas Set - Lightweigh...,31244,-95.461794,29.582652,Charleston SC,-79.9333,32.7833,False,Nice Soft Cotton Sleepwear Pajamas Set - Light...

In [38]:
data_clean['created_at'] = pd.to_datetime(data_clean['created_at'], format='ISO8601')
data_clean['returned_at'] = pd.to_datetime(data_clean['returned_at'], format='ISO8601')
data_clean['shipped_at'] = pd.to_datetime(data_clean['shipped_at'], format='ISO8601')
data_clean['delivered_at'] = pd.to_datetime(data_clean['delivered_at'], format='ISO8601')

In [39]:
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 181926 entries, 0 to 181925
Data columns (total 38 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_id                181926 non-null  int64
 1   user_id                 181926 non-null  int64
 2   status                  181926 non-null  object
 3   gender                  181926 non-null  object
 4   created_at              181926 non-null  datetime64[ns, UTC]
 5   returned_at             18058 non-null   datetime64[ns, UTC]
 6   shipped_at              118018 non-null  datetime64[ns, UTC]
 7   delivered_at            63375 non-null   datetime64[ns, UTC]
 8   num_of_item             181926 non-null  int64
 9   product_id              181926 non-null  int64
 10  inventory_item_id       181926 non-null  int64
 11  sale_price              181926 non-null  float64
 12  first_name              181926 non-null  object
 13  last_name               181926 non-null  object
 14  email                   181926 non-null  object
 15  age                     181926 non-null  int64
 16  state                   181926 non-null  object
 17  street_address          181926 non-null  object
 18  postal_code             181926 non-null  object
 19  city                    180108 non-null  object
 20  country                 181926 non-null  object
 21  traffic_source          181926 non-null  object
 22  cost                    181926 non-null  float64
 23  category                181926 non-null  object
 24  brand                   181742 non-null  object
 25  department              181926 non-null  object
 26  sku                     181926 non-null  object
 27  distribution_center_id  181926 non-null  int64
 28  sold_at                 0 non-null       float64
 29  product_name            181919 non-null  object
 30  order_item_id           181926 non-null  int64
 31  delivery_longitude      181926 non-null  float64
 32  delivery_latitude       181926 non-null  float64
 33  warehouse_name          181926 non-null  object
 34  warehouse_longitude     181926 non-null  float64
 35  warehouse_latitude      181926 non-null  float64
 36  is_loyal                181926 non-null  bool
 37  customer_review         181926 non-null  object
dtypes: bool(1), datetime64[ns, UTC](4), float64(7), int64(8), object(18)
memory usage: 52.9+ MB

### Поработаем с null

In [55]:
data_clean.isna().sum()[data_clean.isna().sum()>0].sort_values(ascending= False)

sold_at         181926
returned_at     163868
delivered_at    118551
shipped_at       63908
city              1818
brand              184
product_name         7
dtype: int64

In [56]:
data_clean =data_clean.drop(columns = 'sold_at')

дозаполнить пробелы в city не получится , так как нет вообще никакой информации у тех user_id о городе

по пропущенным product_name аналогично