In [ ]:
import pandas as pd

# DATA.CSV

### Посмотрим на данные

In [ ]:
data = pd.read_csv("data.csv")

In [ ]:
data.shape

(545778, 49)

In [ ]:
data.head(2)

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item,product_id,...,distribution_center_geom,order_item_id,delivery_longitude,delivery_latitude,warehouse_name,warehouse_longitude,warehouse_latitude,is_loyal,product_name_clean,customer_review
0,118730,94911,Shipped,F,2026-03-11 00:47:27+00:00,NaN,2026-03-12 20:06:27+00:00,NaN,1,2200,...,POINT(-89.9711 35.1174),172697,-92.088678,34.127955,Memphis TN,-89.9711,35.1174,False,Bella Two-Tone Full-Zip Hooded Sweatshirt,Just received the Bella Two-Tone Full-Zip Hood...
1,114939,91961,Shipped,M,2026-03-11 00:46:02+00:00,NaN,2026-03-13 23:10:02+00:00,NaN,2,21920,...,POINT(-95.3698 29.7604),167157,-119.645815,36.534992,Houston TX,-95.3698,29.7604,False,Calvin Klein Sportswear Men's Broken Micro Che...,I really liked this Calvin Klein Sportswear Me...

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545778 entries, 0 to 545777
Data columns (total 49 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   order_id                        545778 non-null  int64
 1   user_id                         545778 non-null  int64
 2   status                          545778 non-null  object
 3   gender                          545778 non-null  object
 4   created_at                      545778 non-null  object
 5   returned_at                     54174 non-null   object
 6   shipped_at                      354054 non-null  object
 7   delivered_at                    190125 non-null  object
 8   num_of_item                     545778 non-null  int64
 9   product_id                      545778 non-null  int64
 10  inventory_item_id               545778 non-null  int64
 11  sale_price                      545778 non-null  float64
 12  id                              545778 non-null  int64
 13  first_name                      545778 non-null  object
 14  last_name                       545778 non-null  object
 15  email                           545778 non-null  object
 16  age                             545778 non-null  int64
 17  state                           545778 non-null  object
 18  street_address                  545778 non-null  object
 19  postal_code                     545778 non-null  object
 20  city                            540324 non-null  object
 21  country                         545778 non-null  object
 22  traffic_source                  545778 non-null  object
 23  user_geom                       545778 non-null  object
 24  cost                            545778 non-null  float64
 25  category                        545778 non-null  object
 26  brand                           545226 non-null  object
 27  retail_price                    545778 non-null  float64
 28  department                      545778 non-null  object
 29  sku                             545778 non-null  object
 30  distribution_center_id          545778 non-null  int64
 31  sold_at                         0 non-null       float64
 32  product_category                545778 non-null  object
 33  product_name                    545757 non-null  object
 34  product_brand                   545226 non-null  object
 35  product_retail_price            545778 non-null  float64
 36  product_department              545778 non-null  object
 37  product_sku                     545778 non-null  object
 38  product_distribution_center_id  545778 non-null  int64
 39  distribution_center_geom        545778 non-null  object
 40  order_item_id                   545778 non-null  int64
 41  delivery_longitude              545778 non-null  float64
 42  delivery_latitude               545778 non-null  float64
 43  warehouse_name                  545778 non-null  object
 44  warehouse_longitude             545778 non-null  float64
 45  warehouse_latitude              545778 non-null  float64
 46  is_loyal                        545778 non-null  bool
 47  product_name_clean              545757 non-null  object
 48  customer_review                 545778 non-null  object
dtypes: bool(1), float64(9), int64(10), object(29)
memory usage: 200.4+ MB

In [ ]:
data.columns

Index(['order_id', 'user_id', 'status', 'gender', 'created_at', 'returned_at',
       'shipped_at', 'delivered_at', 'num_of_item', 'product_id',
       'inventory_item_id', 'sale_price', 'id', 'first_name', 'last_name',
       'email', 'age', 'state', 'street_address', 'postal_code', 'city',
       'country', 'traffic_source', 'user_geom', 'cost', 'category', 'brand',
       'retail_price', 'department', 'sku', 'distribution_center_id',
       'sold_at', 'product_category', 'product_name', 'product_brand',
       'product_retail_price', 'product_department', 'product_sku',
       'product_distribution_center_id', 'distribution_center_geom',
       'order_item_id', 'delivery_longitude', 'delivery_latitude',
       'warehouse_name', 'warehouse_longitude', 'warehouse_latitude',
       'is_loyal', 'product_name_clean', 'customer_review'],
      dtype='object')



*   Поменять формат данных у created_at, returned_at , shipped_at, delivered_at - с object ---> date
*   Удалить столбец sold_at, так как во всех строках нет значений


*   Проверить столбцы с похожими названиями на полное совпадение (по типу brand --- product_brand)
*   Столбцы postal_code -- возможно тоже поменять формат


*   Удалить дублирующиеся строки

### Удалим дубликаты

In [ ]:
data.duplicated().sum()

np.int64(363852)

In [ ]:
data[data.duplicated(keep=False)].sort_values(by=list(data.columns)).head(5)

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item,product_id,...,distribution_center_geom,order_item_id,delivery_longitude,delivery_latitude,warehouse_name,warehouse_longitude,warehouse_latitude,is_loyal,product_name_clean,customer_review
95917,1,1,Complete,M,2024-10-14 10:31:40+00:00,NaN,2024-10-14 20:11:40+00:00,2024-10-19 07:17:40+00:00,1,22533,...,POINT(-118.25 34.05),1,-90.627780,41.588617,Los Angeles CA,-118.2500,34.05,False,KingSize Big & Tall Expandable Waist Wrinkle R...,Just received the KingSize Big & Tall Expandab...
277843,1,1,Complete,M,2024-10-14 10:31:40+00:00,NaN,2024-10-14 20:11:40+00:00,2024-10-19 07:17:40+00:00,1,22533,...,POINT(-118.25 34.05),1,-90.627780,41.588617,Los Angeles CA,-118.2500,34.05,False,KingSize Big & Tall Expandable Waist Wrinkle R...,Just received the KingSize Big & Tall Expandab...
459769,1,1,Complete,M,2024-10-14 10:31:40+00:00,NaN,2024-10-14 20:11:40+00:00,2024-10-19 07:17:40+00:00,1,22533,...,POINT(-118.25 34.05),1,-90.627780,41.588617,Los Angeles CA,-118.2500,34.05,False,KingSize Big & Tall Expandable Waist Wrinkle R...,Just received the KingSize Big & Tall Expandab...
73772,2,2,Complete,F,2025-04-11 13:43:06+00:00,NaN,2025-04-13 07:54:06+00:00,2025-04-16 08:37:06+00:00,2,12982,...,POINT(-90.0667 29.95),3,15.726955,51.221528,New Orleans LA,-90.0667,29.95,True,Lucky Brand My Tribe Banded Halter Top,"As a frequent shopper, I'm thrilled with this ..."
255698,2,2,Complete,F,2025-04-11 13:43:06+00:00,NaN,2025-04-13 07:54:06+00:00,2025-04-16 08:37:06+00:00,2,12982,...,POINT(-90.0667 29.95),3,15.726955,51.221528,New Orleans LA,-90.0667,29.95,True,Lucky Brand My Tribe Banded Halter Top,"As a frequent shopper, I'm thrilled with this ..."

In [ ]:
data1 = data.drop_duplicates()
# оставит первое вхождение

In [ ]:
data1.shape

(181926, 49)

In [ ]:
data1.columns

Index(['order_id', 'user_id', 'status', 'gender', 'created_at', 'returned_at',
       'shipped_at', 'delivered_at', 'num_of_item', 'product_id',
       'inventory_item_id', 'sale_price', 'id', 'first_name', 'last_name',
       'email', 'age', 'state', 'street_address', 'postal_code', 'city',
       'country', 'traffic_source', 'user_geom', 'cost', 'category', 'brand',
       'retail_price', 'department', 'sku', 'distribution_center_id',
       'sold_at', 'product_category', 'product_name', 'product_brand',
       'product_retail_price', 'product_department', 'product_sku',
       'product_distribution_center_id', 'distribution_center_geom',
       'order_item_id', 'delivery_longitude', 'delivery_latitude',
       'warehouse_name', 'warehouse_longitude', 'warehouse_latitude',
       'is_loyal', 'product_name_clean', 'customer_review'],
      dtype='object')

### Проверим столбцы на схожесть

In [ ]:
col = data1.columns
col
to_del = []

for i in range(len(col)):
    for j in range(i + 1, len(col)):
        if data1[data1.columns[i]].equals(data1[data1.columns[j]]):
            print(f"{col[i]:<23} | {col[j]:<23}")
            to_del.append(col[j])

user_id                 | id
sale_price              | retail_price
sale_price              | product_retail_price
category                | product_category
brand                   | product_brand
retail_price            | product_retail_price
department              | product_department
sku                     | product_sku
distribution_center_id  | product_distribution_center_id
product_name            | product_name_clean

In [ ]:
data1[
    [
        "user_geom	delivery_longitude",
        "delivery_latitude",
        "distribution_center_geom",
        "warehouse_longitude",
        "warehouse_latitude",
    ]
]

,user_geom,delivery_longitude,delivery_latitude,distribution_center_geom,warehouse_longitude,warehouse_latitude
0,POINT(-92.0886782 34.12795471),-92.088678,34.127955,POINT(-89.9711 35.1174),-89.9711,35.1174
1,POINT(-119.6458146 36.53499187),-119.645815,36.534992,POINT(-95.3698 29.7604),-95.3698,29.7604
2,POINT(-119.6458146 36.53499187),-119.645815,36.534992,POINT(-75.1667 39.95),-75.1667,39.9500
3,POINT(116.5019973 39.83631574),116.501997,39.836316,POINT(-87.6847 41.8369),-87.6847,41.8369
4,POINT(2.45549956 48.98550893),2.455500,48.985509,POINT(-118.25 34.05),-118.2500,34.0500
...,...,...,...,...,...,...
181921,POINT(-62.4853718 -7.362417987),-62.485372,-7.362418,POINT(-87.6847 41.8369),-87.6847,41.8369
181922,POINT(-62.4853718 -7.362417987),-62.485372,-7.362418,POINT(-88.0431 30.6944),-88.0431,30.6944
181923,POINT(-62.4853718 -7.362417987),-62.485372,-7.362418,POINT(-89.9711 35.1174),-89.9711,35.1174
181924,POINT(-62.4853718 -7.362417987),-62.485372,-7.362418,POINT(-95.3698 29.7604),-95.3698,29.7604
181925,POINT(-95.46179389 29.58265204),-95.461794,29.582652,POINT(-79.9333 32.7833),-79.9333,32.7833

In [ ]:
import re


def extract_coords(point_str):
    match = re.search(r"POINT\(([-\d.]+)\s+([-\d.]+)\)", point_str)
    if match:
        return float(match.group(1)), float(match.group(2))
    return None, None


data1["user_longitude"] = data1["user_geom"].apply(lambda x: extract_coords(x)[0])
data1["user_latitude"] = data1["user_geom"].apply(lambda x: extract_coords(x)[1])

longitude_match = data1["user_longitude"] == data1["delivery_longitude"]
latitude_match = data1["user_latitude"] == data1["delivery_latitude"]

coords_match = longitude_match & latitude_match  # булевы

print(f"Совпадающих координат: {coords_match.sum()}")
print(f"Не совпадающих: {(~coords_match).sum()}")

data1 = data1.drop(columns=["user_longitude", "user_latitude"])

/tmp/ipykernel_5926/2005638555.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['user_longitude'] = data1['user_geom'].apply(lambda x: extract_coords(x)[0])

Совпадающих координат: 181926
Не совпадающих: 0

/tmp/ipykernel_5926/2005638555.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['user_latitude'] = data1['user_geom'].apply(lambda x: extract_coords(x)[1])

In [ ]:
def extract_coords_dist(point_str):
    match = re.search(r"POINT\(([-\d.]+)\s+([-\d.]+)\)", point_str)
    if match:
        return float(match.group(1)), float(match.group(2))
    return None, None


data1["dist_longitude"] = data1["distribution_center_geom"].apply(lambda x: extract_coords(x)[0])
data1["dist_latitude"] = data1["distribution_center_geom"].apply(lambda x: extract_coords(x)[1])

longitude_match = data1["dist_longitude"] == data1["warehouse_longitude"]
latitude_match = data1["dist_latitude"] == data1["warehouse_latitude"]

coords_match = longitude_match & latitude_match

print(f"Совпадающих координат: {coords_match.sum()}")
print(f"Не совпадающих: {(~coords_match).sum()}")

data1 = data1.drop(columns=["dist_longitude", "dist_latitude"])

Совпадающих координат: 181926
Не совпадающих: 0

In [ ]:
to_del.append("distribution_center_geom")
to_del.append("user_geom")

data_clean = data1.drop(columns=to_del)

In [ ]:
to_del

['id',
 'retail_price',
 'product_retail_price',
 'product_category',
 'product_brand',
 'product_retail_price',
 'product_department',
 'product_sku',
 'product_distribution_center_id',
 'product_name_clean',
 'distribution_center_geom',
 'user_geom']

In [ ]:
data_clean.shape

(181926, 38)

In [ ]:
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 181926 entries, 0 to 181925
Data columns (total 38 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_id                181926 non-null  int64
 1   user_id                 181926 non-null  int64
 2   status                  181926 non-null  object
 3   gender                  181926 non-null  object
 4   created_at              181926 non-null  object
 5   returned_at             18058 non-null   object
 6   shipped_at              118018 non-null  object
 7   delivered_at            63375 non-null   object
 8   num_of_item             181926 non-null  int64
 9   product_id              181926 non-null  int64
 10  inventory_item_id       181926 non-null  int64
 11  sale_price              181926 non-null  float64
 12  first_name              181926 non-null  object
 13  last_name               181926 non-null  object
 14  email                   181926 non-null  object
 15  age                     181926 non-null  int64
 16  state                   181926 non-null  object
 17  street_address          181926 non-null  object
 18  postal_code             181926 non-null  object
 19  city                    180108 non-null  object
 20  country                 181926 non-null  object
 21  traffic_source          181926 non-null  object
 22  cost                    181926 non-null  float64
 23  category                181926 non-null  object
 24  brand                   181742 non-null  object
 25  department              181926 non-null  object
 26  sku                     181926 non-null  object
 27  distribution_center_id  181926 non-null  int64
 28  sold_at                 0 non-null       float64
 29  product_name            181919 non-null  object
 30  order_item_id           181926 non-null  int64
 31  delivery_longitude      181926 non-null  float64
 32  delivery_latitude       181926 non-null  float64
 33  warehouse_name          181926 non-null  object
 34  warehouse_longitude     181926 non-null  float64
 35  warehouse_latitude      181926 non-null  float64
 36  is_loyal                181926 non-null  bool
 37  customer_review         181926 non-null  object
dtypes: bool(1), float64(7), int64(8), object(22)
memory usage: 52.9+ MB

### Изменим формат некоторых данных

In [ ]:
data_clean

,order_id,user_id,status,gender,created_at,returned_at,shipped_at,delivered_at,num_of_item,product_id,...,sold_at,product_name,order_item_id,delivery_longitude,delivery_latitude,warehouse_name,warehouse_longitude,warehouse_latitude,is_loyal,customer_review
0,118730,94911,Shipped,F,2026-03-11 00:47:27+00:00,NaN,2026-03-12 20:06:27+00:00,NaN,1,2200,...,NaN,Bella Two-Tone Full-Zip Hooded Sweatshirt,172697,-92.088678,34.127955,Memphis TN,-89.9711,35.1174,False,Just received the Bella Two-Tone Full-Zip Hood...
1,114939,91961,Shipped,M,2026-03-11 00:46:02+00:00,NaN,2026-03-13 23:10:02+00:00,NaN,2,21920,...,NaN,Calvin Klein Sportswear Men's Broken Micro Che...,167157,-119.645815,36.534992,Houston TX,-95.3698,29.7604,False,I really liked this Calvin Klein Sportswear Me...
2,114939,91961,Shipped,M,2026-03-11 00:46:02+00:00,NaN,2026-03-13 23:10:02+00:00,NaN,2,20031,...,NaN,FactoryExtreme Neptune Men's Black Biker Leath...,167158,-119.645815,36.534992,Philadelphia PA,-75.1667,39.9500,False,Nice FactoryExtreme Neptune Men's Black Biker ...
3,99949,79993,Complete,F,2026-03-11 00:39:44.268552+00:00,NaN,2026-03-13 17:24:44.268552+00:00,2026-03-16 01:00:44.268552+00:00,1,15500,...,NaN,HUE Women's 3-Pack Hidden Cotton Liner,145310,116.501997,39.836316,Chicago IL,-87.6847,41.8369,False,Nice HUE Women's 3-Pack Hidden Cotton Liner. W...
4,92967,74352,Shipped,M,2026-03-11 00:39:29.765939+00:00,NaN,2026-03-12 11:30:29.765939+00:00,NaN,1,18572,...,NaN,Zorrel - Insect Shield Apparel Long Sleeve Tee...,135249,2.455500,48.985509,Los Angeles CA,-118.2500,34.0500,False,Good value for money. The Zorrel - Insect Shie...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181921,32199,25808,Shipped,F,2019-01-10 19:40:10+00:00,NaN,2019-01-13 00:21:10+00:00,NaN,4,10095,...,NaN,Midnight By Carole Hochman Women's Swept Away ...,46856,-62.485372,-7.362418,Chicago IL,-87.6847,41.8369,True,"As a frequent shopper, I'm thrilled with this ..."
181922,32199,25808,Shipped,F,2019-01-10 19:40:10+00:00,NaN,2019-01-13 00:21:10+00:00,NaN,4,1836,...,NaN,American Apparel Unisex Dolman Sleeve Hoodie,46858,-62.485372,-7.362418,Mobile AL,-88.0431,30.6944,True,Another 5-star purchase! This American Apparel...
181923,32199,25808,Shipped,F,2019-01-10 19:40:10+00:00,NaN,2019-01-13 00:21:10+00:00,NaN,4,14985,...,NaN,Adjustable Bra Design Front Panel Clasp Matern...,46855,-62.485372,-7.362418,Memphis TN,-89.9711,35.1174,True,"I always order my gear here, and this Adjustab..."
181924,32199,25808,Shipped,F,2019-01-10 19:40:10+00:00,NaN,2019-01-13 00:21:10+00:00,NaN,4,7231,...,NaN,Jones New York Women's Boot Skirt,46857,-62.485372,-7.362418,Houston TX,-95.3698,29.7604,True,Best brand ever. This Jones New York Women's B...
181925,21439,17102,Processing,F,2019-01-04 03:52:40+00:00,NaN,NaN,NaN,1,9952,...,NaN,Soft Cotton Sleepwear Pajamas Set - Lightweigh...,31244,-95.461794,29.582652,Charleston SC,-79.9333,32.7833,False,Nice Soft Cotton Sleepwear Pajamas Set - Light...

In [ ]:
data_clean["created_at"] = pd.to_datetime(data_clean["created_at"], format="ISO8601")
data_clean["returned_at"] = pd.to_datetime(data_clean["returned_at"], format="ISO8601")
data_clean["shipped_at"] = pd.to_datetime(data_clean["shipped_at"], format="ISO8601")
data_clean["delivered_at"] = pd.to_datetime(data_clean["delivered_at"], format="ISO8601")

In [ ]:
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 181926 entries, 0 to 181925
Data columns (total 38 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_id                181926 non-null  int64
 1   user_id                 181926 non-null  int64
 2   status                  181926 non-null  object
 3   gender                  181926 non-null  object
 4   created_at              181926 non-null  datetime64[ns, UTC]
 5   returned_at             18058 non-null   datetime64[ns, UTC]
 6   shipped_at              118018 non-null  datetime64[ns, UTC]
 7   delivered_at            63375 non-null   datetime64[ns, UTC]
 8   num_of_item             181926 non-null  int64
 9   product_id              181926 non-null  int64
 10  inventory_item_id       181926 non-null  int64
 11  sale_price              181926 non-null  float64
 12  first_name              181926 non-null  object
 13  last_name               181926 non-null  object
 14  email                   181926 non-null  object
 15  age                     181926 non-null  int64
 16  state                   181926 non-null  object
 17  street_address          181926 non-null  object
 18  postal_code             181926 non-null  object
 19  city                    180108 non-null  object
 20  country                 181926 non-null  object
 21  traffic_source          181926 non-null  object
 22  cost                    181926 non-null  float64
 23  category                181926 non-null  object
 24  brand                   181742 non-null  object
 25  department              181926 non-null  object
 26  sku                     181926 non-null  object
 27  distribution_center_id  181926 non-null  int64
 28  sold_at                 0 non-null       float64
 29  product_name            181919 non-null  object
 30  order_item_id           181926 non-null  int64
 31  delivery_longitude      181926 non-null  float64
 32  delivery_latitude       181926 non-null  float64
 33  warehouse_name          181926 non-null  object
 34  warehouse_longitude     181926 non-null  float64
 35  warehouse_latitude      181926 non-null  float64
 36  is_loyal                181926 non-null  bool
 37  customer_review         181926 non-null  object
dtypes: bool(1), datetime64[ns, UTC](4), float64(7), int64(8), object(18)
memory usage: 52.9+ MB

### Поработаем с null

In [ ]:
data_clean.isna().sum()[data_clean.isna().sum() > 0].sort_values(ascending=False)

sold_at         181926
returned_at     163868
delivered_at    118551
shipped_at       63908
city              1818
brand              184
product_name         7
dtype: int64

In [ ]:
data_clean = data_clean.drop(columns="sold_at")

In [ ]:
data_clean.columns

Index(['order_id', 'user_id', 'status', 'gender', 'created_at', 'returned_at',
       'shipped_at', 'delivered_at', 'num_of_item', 'product_id',
       'inventory_item_id', 'sale_price', 'first_name', 'last_name', 'email',
       'age', 'state', 'street_address', 'postal_code', 'city', 'country',
       'traffic_source', 'cost', 'category', 'brand', 'department', 'sku',
       'distribution_center_id', 'product_name', 'order_item_id',
       'delivery_longitude', 'delivery_latitude', 'warehouse_name',
       'warehouse_longitude', 'warehouse_latitude', 'is_loyal',
       'customer_review'],
      dtype='object')

In [ ]:
len(data_clean.columns)

37

In [ ]:
data_clean.shape

(181926, 37)

дозаполнить пробелы в city не получится , так как нет вообще никакой информации у тех user_id о городе

по пропущенным product_name аналогично

### Итого столбцы

In [ ]:
description = pd.DataFrame(
    {
        "Name": data_clean.columns,
        "Desc": [
            "Уникальный номер заказа",
            "Уникальный айди покупателя",
            "Статус заказа",
            "Пол покупателя",
            "Дата создания заказа",
            "Дата возврата заказа",
            "Дата отправки заказа",
            "Дата доставки заказа",
            "Количество товаров (?)",
            "Айди товара",
            "inventory_item_id (?)",
            "Цена со скидкой",
            "Имя",
            "Фамилия",
            "Почта",
            "возраст",
            "Штат",
            "Адрес покупателя",
            "Почтовый индекс",
            "Город",
            "Страна",
            "traffic_source (?)",
            "Цена",
            "Категория товара",
            "Брэнд товара",
            "department",
            "sku",
            "Айдишник распределительного центра",
            "Наименование товара",
            "order_item_id (?)",
            "Координата долготы юзера",
            "Координата широты юзера",
            "Название склада",
            "Координата долготы warehouse",
            "Координата долготы warehouse",
            "Лоялен?",
            "Отзыв",
        ],
    }
)

description

                      Name                          Desc
0                 order_id       Уникальный номер заказа
1                  user_id    Уникальный айди покупателя
2                   status                 Статус заказа
3                   gender                Пол покупателя
4               created_at          Дата создания заказа
5              returned_at                 Дата возврата
6               shipped_at                 Дата отправки
7             delivered_at                 Дата доставки
8              num_of_item                   num_of_item
9               product_id                   Айди товара
10       inventory_item_id             inventory_item_id
11              sale_price               Цена со скидкой
12              first_name                           Имя
13               last_name                       Фамилия
14                   email                         Почта
15                     age                       возраст
16                   state                         state
17          street_address              Адрес покупателя
18             postal_code               Почтовый индекс
19                    city                         Город
20                 country                        Страна
21          traffic_source               traffic_source
22                    cost                          Цена
23                category              Категория товара
24                   brand                  Брэнд товара
25              department                    department
26                     sku                           sku
27  distribution_center_id        distribution_center_id
28            product_name           Наименование товара
29           order_item_id                 order_item_id
30      delivery_longitude      Координата долготы юзера
31       delivery_latitude       Координата широты юзера
32          warehouse_name                warehouse_name
33     warehouse_longitude  Координата долготы warehouse
34      warehouse_latitude  Координата долготы warehouse
35                is_loyal                       Лоялен?
36         customer_review                         Отзыв

# EVENT.CSV

### Посмотрим на данные

In [ ]:
import pandas as pd
from google.colab import drive

drive.mount("/content/drive")

file_path = "/content/drive/MyDrive/events.csv"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
events = pd.read_csv(file_path)

In [ ]:
events

,id,user_id,sequence_number,session_id,created_at,ip_address,city,state,postal_code,browser,traffic_source,uri,event_type
0,1840721,NaN,3,32c825f3-2e85-4f79-ad2b-188d3ae22785,2022-12-27 02:05:00+00:00,153.11.214.106,São Paulo,São Paulo,02675-031,Chrome,Email,/cancel,cancel
1,1677966,NaN,3,1e21f050-a916-4863-94a0-2a4e474d60c2,2024-06-30 16:04:00+00:00,62.51.52.204,São Paulo,São Paulo,02675-031,Firefox,Adwords,/cancel,cancel
2,1440516,NaN,3,239ccdcb-c9b8-4cab-8203-ef7c4215526f,2024-02-19 07:16:00+00:00,91.225.208.255,São Paulo,São Paulo,02675-031,Chrome,Email,/cancel,cancel
3,1967607,NaN,3,b9082731-7773-4371-b03c-c93d702d7feb,2020-07-17 14:39:00+00:00,90.150.5.159,Aomori City,Aomori,038-0042,Other,Adwords,/cancel,cancel
4,2068472,NaN,3,73feafb9-135d-47eb-8b82-dc73342edf81,2024-09-29 07:56:00+00:00,151.108.206.70,Huanggang,Beijing,100010,Firefox,Adwords,/cancel,cancel
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4865319,957931,73130.0,7,8ee43770-d0a2-47b6-9c40-6397ece27683,2025-12-22 15:00:15+00:00,123.5.134.160,Northolt,England,UB5,Chrome,Email,/purchase,purchase
4865320,179507,13521.0,7,3ae1b740-54a5-497a-88e8-060aabd2f098,2023-08-28 14:13:05+00:00,126.144.194.193,London,England,W9,IE,Adwords,/purchase,purchase
4865321,393641,30019.0,7,097eae72-f037-42a9-9ab5-b229ad630f10,2025-11-05 00:02:22+00:00,58.245.136.0,Dewsbury,England,WF12,Chrome,Email,/purchase,purchase
4865322,220770,16714.0,10,beaf1322-c5b3-4175-b93f-f0445d27d8aa,2025-10-31 22:52:25+00:00,169.98.203.100,Scarborough,England,YO12,Firefox,Facebook,/purchase,purchase
4865323,220750,16714.0,10,b5e7d6a9-e5dd-4805-b00d-b30c3345e7a2,2025-11-04 23:37:02+00:00,49.239.13.232,Scarborough,England,YO12,Chrome,Adwords,/purchase,purchase

In [ ]:
events.shape

(4865324, 13)

In [ ]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4865324 entries, 0 to 4865323
Data columns (total 13 columns):
 #   Column           Dtype
---  ------           -----
 0   id               int64
 1   user_id          float64
 2   sequence_number  int64
 3   session_id       object
 4   created_at       object
 5   ip_address       object
 6   city             object
 7   state            object
 8   postal_code      object
 9   browser          object
 10  traffic_source   object
 11  uri              object
 12  event_type       object
dtypes: float64(1), int64(2), object(10)
memory usage: 482.6+ MB

### Удалим дубликаты

In [ ]:
events.duplicated().sum()

np.int64(2432662)

In [ ]:
events[events.duplicated(keep=False)].sort_values(by=list(events.columns)).head(5)

,id,user_id,sequence_number,session_id,created_at,ip_address,city,state,postal_code,browser,traffic_source,uri,event_type
637491,1,1.0,1,cbc67bbb-3641-4955-9efa-c1a1d7bbbc3a,2024-10-14 10:14:35+00:00,23.55.76.194,Davenport,Iowa,52806,Firefox,Email,/home,home
3070153,1,1.0,1,cbc67bbb-3641-4955-9efa-c1a1d7bbbc3a,2024-10-14 10:14:35+00:00,23.55.76.194,Davenport,Iowa,52806,Firefox,Email,/home,home
400574,2,1.0,2,cbc67bbb-3641-4955-9efa-c1a1d7bbbc3a,2024-10-14 10:15:44+00:00,23.55.76.194,Davenport,Iowa,52806,Firefox,Email,/department/men/category/pants/brand/kingsize,department
2833236,2,1.0,2,cbc67bbb-3641-4955-9efa-c1a1d7bbbc3a,2024-10-14 10:15:44+00:00,23.55.76.194,Davenport,Iowa,52806,Firefox,Email,/department/men/category/pants/brand/kingsize,department
851034,3,1.0,3,cbc67bbb-3641-4955-9efa-c1a1d7bbbc3a,2024-10-14 10:17:07+00:00,23.55.76.194,Davenport,Iowa,52806,Firefox,Email,/product/22533,product

In [ ]:
events1 = events.drop_duplicates()
# оставит первое вхождение

In [ ]:
events1.shape

(2432662, 13)

### Работа с null

In [ ]:
events1.isnull().sum()[events1.isnull().sum() > 0]

user_id    1124244
city         24065
dtype: int64

In [ ]:
events1[events1["user_id"].isna()][["user_id", "ip_address"]]

         user_id      ip_address
0            NaN  153.11.214.106
1            NaN    62.51.52.204
2            NaN  91.225.208.255
3            NaN    90.150.5.159
4            NaN  151.108.206.70
...          ...             ...
2430802      NaN   69.247.187.77
2430804      NaN  10.228.254.231
2430805      NaN  213.164.203.37
2430806      NaN       4.36.37.4
2430807      NaN   12.179.78.247

[1124244 rows x 2 columns]

In [ ]:
# Находим все ip_address, у которых есть null user_id
null_ips = events1[events1["user_id"].isna()]["ip_address"].unique()

# Выводим строки с not null user_id, у которых ip_address входит в этот список
events1[events1["user_id"].notna() & events1["ip_address"].isin(null_ips)][
    ["user_id", "ip_address"]
]

         user_id       ip_address
1978     35496.0  214.247.107.215
8018     69200.0  104.180.124.159
8029     92776.0   137.49.190.105
37464    31448.0   99.166.114.251
39650    31448.0   99.166.114.251
...          ...              ...
2391802   8795.0   92.102.202.216
2399141  99873.0   186.82.106.192
2405647  31448.0   99.166.114.251
2411004  31448.0   99.166.114.251
2417816  59894.0    14.65.235.235

[188 rows x 2 columns]

In [ ]:
# Создаем словарь: ip -> user_id
ip_to_user = events1[events1["user_id"].notna()].set_index("ip_address")["user_id"].to_dict()

# Заполняем пропуски
events1["user_id"] = events1["user_id"].fillna(events1["ip_address"].map(ip_to_user))

/tmp/ipykernel_18356/787946338.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events1['user_id'] = events1['user_id'].fillna(events1['ip_address'].map(ip_to_user))

In [ ]:
events1[["user_id", "ip_address"]][events1["ip_address"] == "214.247.107.215"]

         user_id       ip_address
1978     35496.0  214.247.107.215
102574   35496.0  214.247.107.215
218695   35496.0  214.247.107.215
485744   35496.0  214.247.107.215
553436   35496.0  214.247.107.215
878590   35496.0  214.247.107.215
929387   35496.0  214.247.107.215
1006856  35496.0  214.247.107.215
1280318  35496.0  214.247.107.215
1747943  35496.0  214.247.107.215
1867345  35496.0  214.247.107.215
2269529  35496.0  214.247.107.215

In [ ]:
events1[events1["user_id"].isna()][["user_id", "ip_address"]]

         user_id      ip_address
0            NaN  153.11.214.106
1            NaN    62.51.52.204
2            NaN  91.225.208.255
3            NaN    90.150.5.159
4            NaN  151.108.206.70
...          ...             ...
2430802      NaN   69.247.187.77
2430804      NaN  10.228.254.231
2430805      NaN  213.164.203.37
2430806      NaN       4.36.37.4
2430807      NaN   12.179.78.247

[1124189 rows x 2 columns]

In [ ]:
events1[["user_id", "ip_address"]][events1["ip_address"] == "91.225.208.255"]

         user_id      ip_address
2            NaN  91.225.208.255
433165       NaN  91.225.208.255
1694062      NaN  91.225.208.255

In [ ]:
events1[events1["city"].isna()][["city", "ip_address"]]

        city       ip_address
372      NaN    125.0.122.179
692      NaN  151.144.111.135
884      NaN   188.153.71.226
918      NaN   76.111.215.187
919      NaN   209.66.166.253
...      ...              ...
2432066  NaN   74.146.226.189
2432095  NaN  181.118.175.173
2432143  NaN  157.100.241.100
2432169  NaN    46.12.228.208
2432170  NaN    56.148.53.248

[24065 rows x 2 columns]

In [ ]:
# Находим все ip_address, у которых есть null user_id
null_ips1 = events1[events1["city"].isna()]["ip_address"].unique()

# Выводим строки с not null user_id, у которых ip_address входит в этот список
events1[events1["city"].notna() & events1["ip_address"].isin(null_ips1)][["city", "ip_address"]]

             city       ip_address
56212     Modesto  133.135.240.199
174752    Modesto  133.135.240.199
691242   Nanchang    204.142.34.62
1249476  Nanchang    204.142.34.62
1439382  Nanchang    204.142.34.62
1982943  Nanchang    204.142.34.62
2017364  Nanchang    204.142.34.62
2028567   Modesto  133.135.240.199

In [ ]:
# Создаем словарь: ip -> user_id
ip_to_city = events1[events1["city"].notna()].set_index("ip_address")["city"].to_dict()

# Заполняем пропуски
events1["city"] = events1["city"].fillna(events1["ip_address"].map(ip_to_city))

/tmp/ipykernel_18356/2507817231.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  events1['city'] = events1['city'].fillna(events1['ip_address'].map(ip_to_city))

In [ ]:
events1.isnull().sum()[events1.isnull().sum() > 0]

user_id    1124189
city         24059
dtype: int64